name:                aws-lambda-haskell
version:             0.1.0.0
github:              "githubuser/aws-lambda-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aws-lambda-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
default-extensions:
- NoImplicitPrelude
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - time
    - text
    - req
    - data-default-class
    - aeson

executables:
  aws-lambda-haskell-simple-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell

tests:
  aws-lambda-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell
