name:                aws-lambda-haskell
version:             0.1.0.0
github:              "jesuspc/aws-lambda-haskell"
license:             BSD3
author:              "Jesús Prieto Colomina"
maintainer:          "chus1818@gmail.com"
copyright:           "2018 Jesús Prieto Colomina"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            This package makes it easy to run AWS Lambda Functions written in Haskell.
category:            AWS

description:         Please see the README on GitHub at <https://github.com/jesuspc/aws-lambda-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
default-extensions:
- NoImplicitPrelude
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - time
    - text
    - req
    - data-default-class
    - aeson

executables:
  aws-lambda-haskell-simple-example-exe:
    main:                Main.hs
    source-dirs:         examples/simple
    ghc-options:
    # - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - aws-lambda-haskell

