#!/usr/bin/env bash

aws iam create-role --role-name lambda-demo --assume-role-policy-document file://trust-policy.json

aws iam attach-role-policy --role-name lambda-demo --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

aws lambda create-function --function-name demo \
--role "arn:aws:iam::300766401287:role/lambda-demo" \
--runtime provided --timeout 15 --memory-size 128 \
--handler demo --zip-file fileb://demo.zip

aws lambda invoke --function-name demo --payload '{"answer":42}' output.txt
